basic:
    name: 'https://uaii.org/'
    environments:
        production: 'https://uaii.org/'
        staging: 'https://appdne70vx.wpdns.site/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /contact/our-locations
        - /tribal-govt-relations
        - /request-services
        - /get-involved/why-donate
        - /health-services
        - /health-services/medical
        - /health-services/dental
        - /health-services/behavioral
        - /health-services/covid
        - /health-services/visit-clinic
        - /community-services
        - /community-services/family-services
        - /community-services/social-services
        - /community-services/domestic-violence-sexual-assault
        - /youth-programs
        - /youth-programs/archery
        - /youth-programs/basketball
        - /youth-programs/bear-tracks
        - /youth-programs/cheer
        - /youth-programs/flag-football
        - /youth-programs/sage-project
        - /events
        - /get-involved
        - /get-involved/volunteer
        - /get-involved/careers-at-uaii
        - /who-we-are
        - /who-we-are/native-community
        - /who-we-are/meet-team
        - /news
        - /contact
        - /news/category/announcements
        - /news/category/blog-post
        - /news/press-release-jim-alexander-interm-ceo
        - /privacy-policy
        - /nondiscrimination
        - /good-faith-estimate
        - /opt-out-preferences
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: '5'
        workers_nonproduction: '5'
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
